### ISSUE TITLE
doest work when app is in release mode 

### ISSUE THREAD

**Issue by AMANUELAB** [apoorvpandey/push_notification#1]
doest work when app is in release mode

**Comment by apoorvpandey** [comment]
Can you show me your code? And also any specific error that you are facing

**Comment by apoorvpandey** [comment]
> doest work when app is in release mode

Can you show me your code? And also can you let me know if you are facing any specific error.

Thanks!

**Comment by apoorvpandey** [comment]
> doest work when app is in release mode
Closing the issue since no details are provided.
